/**
 * The mock part catalogue (50 parts) and target-variance helpers.
 *
 * original chunk: parts-CCEXtbKP.js
 * original exports: a=partStatus, i=REGIONS, n=PROCESSES, o=variancePct, r=PROGRAMMES, t=PARTS
 */

export type ProcessName = "Stamping" | "Sand cast" | "Die cast";
export type Programme = "HDT-2027" | "MDT-2026" | "LDT-Urban" | "BEV-PLT-2";
export type Region = "EU" | "Turkey" | "Mexico" | "India";
/** Estimate against target: over/under beyond ±5%, `pending` without a target. */
export type PartStatus = "pending" | "over" | "under" | "on";

export interface Part {
  name: string;
  number: string;
  process: ProcessName;
  material: string;
  weightKg: number;
  /** Current estimate, EUR per piece. */
  estimate: number;
  target: number | null;
  programme: Programme;
  engineer: string;
  region: Region;
  revision: string;
  annualVolume: number;
  /** ISO date. */
  date: string;
}

/** Percentage the estimate sits above (+) or below (−) target; `null` without a target. */
export function variancePct(part: { estimate: number; target?: number | null }): number | null {
  return part.target == null ? null : ((part.estimate - part.target) / part.target) * 100;
}

export function partStatus(part: { estimate: number; target?: number | null }): PartStatus {
  const variance = variancePct(part);
  return variance == null ? "pending" : variance > 5 ? "over" : variance < -5 ? "under" : "on";
}

export const PROGRAMMES: Programme[] = ["HDT-2027", "MDT-2026", "LDT-Urban", "BEV-PLT-2"];

export const REGIONS: Region[] = ["EU", "Turkey", "Mexico", "India"];

export const PROCESSES: ProcessName[] = ["Stamping", "Sand cast", "Die cast"];

export const PARTS: Part[] = [
  {
    name: "Bearing Housing",
    number: "DTV-HSG-0431",
    process: "Sand cast",
    material: "GG25",
    weightKg: 12.4,
    estimate: 48.2,
    target: 42,
    programme: "HDT-2027",
    engineer: "R. Ehlers",
    region: "EU",
    revision: "B",
    annualVolume: 2000,
    date: "2026-04-28",
  },
  {
    name: "Gearbox End Cover",
    number: "DTV-CVR-0288",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 2.8,
    estimate: 19.6,
    target: 22,
    programme: "MDT-2026",
    engineer: "A. Silva",
    region: "Turkey",
    revision: "C",
    annualVolume: 14000,
    date: "2026-06-11",
  },
  {
    name: "Cab Mount Bracket",
    number: "DTV-BRK-0117",
    process: "Stamping",
    material: "HC340LA",
    weightKg: 1.15,
    estimate: 4.85,
    target: 5.2,
    programme: "HDT-2027",
    engineer: "M. Okonkwo",
    region: "EU",
    revision: "B",
    annualVolume: 24000,
    date: "2026-05-21",
  },
  {
    name: "Air Tank Strap",
    number: "DTV-BRK-0342",
    process: "Stamping",
    material: "DC04",
    weightKg: 0.62,
    estimate: 2.4,
    target: 2.2,
    programme: "LDT-Urban",
    engineer: "Design Operator",
    region: "Mexico",
    revision: "A",
    annualVolume: 38000,
    date: "2026-07-02",
  },
  {
    name: "Differential Carrier",
    number: "DTV-HSG-0509",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 26.8,
    estimate: 112.4,
    target: 118,
    programme: "HDT-2027",
    engineer: "L. Bergmann",
    region: "EU",
    revision: "D",
    annualVolume: 900,
    date: "2026-03-19",
  },
  {
    name: "Oil Pan",
    number: "DTV-PAN-0073",
    process: "Die cast",
    material: "AlSi9Cu3",
    weightKg: 4.6,
    estimate: 31.75,
    target: 30,
    programme: "MDT-2026",
    engineer: "A. Silva",
    region: "Turkey",
    revision: "C",
    annualVolume: 8000,
    date: "2026-07-02",
  },
  {
    name: "Battery Box Panel",
    number: "DTV-PNL-0196",
    process: "Stamping",
    material: "DC04",
    weightKg: 3.4,
    estimate: 11.2,
    target: 12.5,
    programme: "BEV-PLT-2",
    engineer: "R. Ehlers",
    region: "EU",
    revision: "B",
    annualVolume: 6500,
    date: "2026-06-24",
  },
  {
    name: "Steering Bracket",
    number: "DTV-BRK-0455",
    process: "Stamping",
    material: "DP600",
    weightKg: 1.85,
    estimate: 8.9,
    target: null,
    programme: "MDT-2026",
    engineer: "M. Okonkwo",
    region: "India",
    revision: "A",
    annualVolume: 12000,
    date: "2026-07-14",
  },
  {
    name: "Water Pump Housing",
    number: "DTV-HSG-0362",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 1.95,
    estimate: 14.3,
    target: 14,
    programme: "LDT-Urban",
    engineer: "Design Operator",
    region: "Mexico",
    revision: "B",
    annualVolume: 21000,
    date: "2026-05-08",
  },
  {
    name: "Turbo Mount Flange",
    number: "DTV-FLG-0221",
    process: "Sand cast",
    material: "GS-52",
    weightKg: 3.2,
    estimate: 22.6,
    target: 25,
    programme: "HDT-2027",
    engineer: "L. Bergmann",
    region: "EU",
    revision: "A",
    annualVolume: 3400,
    date: "2026-04-02",
  },
  {
    name: "Suspension Reinforcement",
    number: "DTV-BRK-6843",
    process: "Stamping",
    material: "Al 5754",
    weightKg: 4.95,
    estimate: 39.72,
    target: 35.11,
    programme: "HDT-2027",
    engineer: "L. Bergmann",
    region: "Turkey",
    revision: "B",
    annualVolume: 43896,
    date: "2026-07-03",
  },
  {
    name: "Battery Shield",
    number: "DTV-PNL-6997",
    process: "Stamping",
    material: "DC01",
    weightKg: 3.33,
    estimate: 11.54,
    target: 14.43,
    programme: "HDT-2027",
    engineer: "L. Bergmann",
    region: "Mexico",
    revision: "C",
    annualVolume: 24280,
    date: "2026-03-23",
  },
  {
    name: "Axle Clip",
    number: "DTV-BRK-7231",
    process: "Stamping",
    material: "HC340LA",
    weightKg: 5.29,
    estimate: 17.07,
    target: 17.47,
    programme: "MDT-2026",
    engineer: "Design Operator",
    region: "India",
    revision: "A",
    annualVolume: 35402,
    date: "2026-03-25",
  },
  {
    name: "Mirror Shield",
    number: "DTV-PNL-9965",
    process: "Stamping",
    material: "Al 5754",
    weightKg: 0.74,
    estimate: 5.94,
    target: 6,
    programme: "BEV-PLT-2",
    engineer: "R. Ehlers",
    region: "EU",
    revision: "B",
    annualVolume: 30949,
    date: "2026-06-16",
  },
  {
    name: "Filter Clip",
    number: "DTV-BRK-8184",
    process: "Stamping",
    material: "1.4301",
    weightKg: 4.27,
    estimate: 40.74,
    target: 40.4,
    programme: "BEV-PLT-2",
    engineer: "M. Okonkwo",
    region: "EU",
    revision: "B",
    annualVolume: 52645,
    date: "2026-05-10",
  },
  {
    name: "Rear Panel",
    number: "DTV-PNL-3234",
    process: "Stamping",
    material: "DP600",
    weightKg: 1.26,
    estimate: 4.81,
    target: 4.43,
    programme: "HDT-2027",
    engineer: "A. Silva",
    region: "India",
    revision: "B",
    annualVolume: 24227,
    date: "2026-05-13",
  },
  {
    name: "Exhaust Reinforcement",
    number: "DTV-BRK-9848",
    process: "Stamping",
    material: "DP600",
    weightKg: 1.88,
    estimate: 6.32,
    target: 8.09,
    programme: "MDT-2026",
    engineer: "A. Silva",
    region: "EU",
    revision: "A",
    annualVolume: 35216,
    date: "2026-04-22",
  },
  {
    name: "Cooler Strap",
    number: "DTV-STR-9519",
    process: "Stamping",
    material: "DP600",
    weightKg: 1.62,
    estimate: 5.82,
    target: 7.66,
    programme: "LDT-Urban",
    engineer: "L. Bergmann",
    region: "Mexico",
    revision: "A",
    annualVolume: 26476,
    date: "2026-02-05",
  },
  {
    name: "Alternator Shield",
    number: "DTV-PNL-7920",
    process: "Stamping",
    material: "Al 5754",
    weightKg: 5.2,
    estimate: 41.73,
    target: 36.39,
    programme: "BEV-PLT-2",
    engineer: "Design Operator",
    region: "India",
    revision: "B",
    annualVolume: 59116,
    date: "2026-07-26",
  },
  {
    name: "Cab Bracket",
    number: "DTV-BRK-1683",
    process: "Stamping",
    material: "DC04",
    weightKg: 3.04,
    estimate: 9.76,
    target: 8.53,
    programme: "HDT-2027",
    engineer: "R. Ehlers",
    region: "Turkey",
    revision: "C",
    annualVolume: 15204,
    date: "2026-04-20",
  },
  {
    name: "Upper Bracket",
    number: "DTV-BRK-9953",
    process: "Stamping",
    material: "1.4301",
    weightKg: 5.71,
    estimate: 54.48,
    target: null,
    programme: "LDT-Urban",
    engineer: "M. Okonkwo",
    region: "Mexico",
    revision: "B",
    annualVolume: 48243,
    date: "2026-05-05",
  },
  {
    name: "Battery Bracket",
    number: "DTV-BRK-5917",
    process: "Stamping",
    material: "HC340LA",
    weightKg: 0.96,
    estimate: 4.38,
    target: 3.91,
    programme: "LDT-Urban",
    engineer: "Design Operator",
    region: "Turkey",
    revision: "C",
    annualVolume: 17444,
    date: "2026-02-24",
  },
  {
    name: "Fuel Bracket",
    number: "DTV-BRK-2508",
    process: "Stamping",
    material: "1.4301",
    weightKg: 1.47,
    estimate: 14.03,
    target: 15.23,
    programme: "HDT-2027",
    engineer: "M. Okonkwo",
    region: "Mexico",
    revision: "A",
    annualVolume: 57685,
    date: "2026-06-10",
  },
  {
    name: "Wiring Panel",
    number: "DTV-PNL-6145",
    process: "Stamping",
    material: "DC01",
    weightKg: 4.7,
    estimate: 14.61,
    target: 14.49,
    programme: "BEV-PLT-2",
    engineer: "A. Silva",
    region: "Turkey",
    revision: "C",
    annualVolume: 48188,
    date: "2026-03-26",
  },
  {
    name: "Front Clip",
    number: "DTV-BRK-9094",
    process: "Stamping",
    material: "1.4301",
    weightKg: 2.33,
    estimate: 22.23,
    target: null,
    programme: "LDT-Urban",
    engineer: "Design Operator",
    region: "Mexico",
    revision: "B",
    annualVolume: 38948,
    date: "2026-04-07",
  },
  {
    name: "Cab Bracket",
    number: "DTV-BRK-4453",
    process: "Stamping",
    material: "1.4301",
    weightKg: 1.56,
    estimate: 14.88,
    target: 14.91,
    programme: "LDT-Urban",
    engineer: "R. Ehlers",
    region: "EU",
    revision: "B",
    annualVolume: 47994,
    date: "2026-02-16",
  },
  {
    name: "Tank Cover Plate",
    number: "DTV-CVR-2826",
    process: "Stamping",
    material: "1.4301",
    weightKg: 4.36,
    estimate: 41.6,
    target: 46.55,
    programme: "BEV-PLT-2",
    engineer: "Design Operator",
    region: "India",
    revision: "A",
    annualVolume: 29791,
    date: "2026-02-26",
  },
  {
    name: "Front Shield",
    number: "DTV-PNL-2549",
    process: "Stamping",
    material: "Al 5754",
    weightKg: 1.21,
    estimate: 9.71,
    target: 10.57,
    programme: "BEV-PLT-2",
    engineer: "M. Okonkwo",
    region: "Turkey",
    revision: "C",
    annualVolume: 50982,
    date: "2026-03-20",
  },
  {
    name: "Filter Bearing Cap",
    number: "DTV-CAP-7651",
    process: "Sand cast",
    material: "GG25",
    weightKg: 7.8,
    estimate: 34.63,
    target: 41.43,
    programme: "MDT-2026",
    engineer: "R. Ehlers",
    region: "Mexico",
    revision: "A",
    annualVolume: 2781,
    date: "2026-05-28",
  },
  {
    name: "Radiator Manifold",
    number: "DTV-MAN-3658",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 21.5,
    estimate: 92.74,
    target: 114.19,
    programme: "BEV-PLT-2",
    engineer: "L. Bergmann",
    region: "India",
    revision: "C",
    annualVolume: 2647,
    date: "2026-02-24",
  },
  {
    name: "Front Carrier",
    number: "DTV-HSG-9937",
    process: "Sand cast",
    material: "GG25",
    weightKg: 22.7,
    estimate: 93.96,
    target: 92.43,
    programme: "BEV-PLT-2",
    engineer: "L. Bergmann",
    region: "EU",
    revision: "C",
    annualVolume: 564,
    date: "2026-03-06",
  },
  {
    name: "Steering Housing",
    number: "DTV-HSG-5941",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 15.1,
    estimate: 64.61,
    target: 70.67,
    programme: "HDT-2027",
    engineer: "R. Ehlers",
    region: "India",
    revision: "C",
    annualVolume: 1430,
    date: "2026-03-07",
  },
  {
    name: "Battery Housing",
    number: "DTV-HSG-4339",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 31.1,
    estimate: 134.74,
    target: 108.23,
    programme: "BEV-PLT-2",
    engineer: "L. Bergmann",
    region: "India",
    revision: "C",
    annualVolume: 8891,
    date: "2026-03-23",
  },
  {
    name: "Turbo Carrier",
    number: "DTV-HSG-3658",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 28.9,
    estimate: 124.89,
    target: 136.28,
    programme: "HDT-2027",
    engineer: "Design Operator",
    region: "India",
    revision: "B",
    annualVolume: 3819,
    date: "2026-05-05",
  },
  {
    name: "Cab Housing",
    number: "DTV-HSG-7854",
    process: "Sand cast",
    material: "GS-52",
    weightKg: 27.8,
    estimate: 111.81,
    target: null,
    programme: "LDT-Urban",
    engineer: "A. Silva",
    region: "Mexico",
    revision: "A",
    annualVolume: 2504,
    date: "2026-03-23",
  },
  {
    name: "Brake Flange",
    number: "DTV-FLG-5982",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 11.1,
    estimate: 51.9,
    target: 50.42,
    programme: "BEV-PLT-2",
    engineer: "M. Okonkwo",
    region: "India",
    revision: "A",
    annualVolume: 4165,
    date: "2026-03-23",
  },
  {
    name: "Front Manifold",
    number: "DTV-MAN-4468",
    process: "Sand cast",
    material: "GS-52",
    weightKg: 14.8,
    estimate: 65.3,
    target: 56.92,
    programme: "LDT-Urban",
    engineer: "L. Bergmann",
    region: "EU",
    revision: "A",
    annualVolume: 796,
    date: "2026-05-11",
  },
  {
    name: "Engine Carrier",
    number: "DTV-HSG-3780",
    process: "Sand cast",
    material: "GG25",
    weightKg: 39,
    estimate: 145.24,
    target: 117.88,
    programme: "BEV-PLT-2",
    engineer: "M. Okonkwo",
    region: "India",
    revision: "A",
    annualVolume: 3474,
    date: "2026-04-25",
  },
  {
    name: "Pump Bearing Cap",
    number: "DTV-CAP-4341",
    process: "Sand cast",
    material: "GGG40",
    weightKg: 37,
    estimate: 150.33,
    target: 192.39,
    programme: "HDT-2027",
    engineer: "R. Ehlers",
    region: "Mexico",
    revision: "A",
    annualVolume: 3503,
    date: "2026-05-03",
  },
  {
    name: "Step Bearing Cap",
    number: "DTV-CAP-2247",
    process: "Sand cast",
    material: "GG25",
    weightKg: 34.7,
    estimate: 129.11,
    target: 133.01,
    programme: "HDT-2027",
    engineer: "L. Bergmann",
    region: "Turkey",
    revision: "A",
    annualVolume: 7344,
    date: "2026-04-20",
  },
  {
    name: "Turbo Housing",
    number: "DTV-HSG-4194",
    process: "Die cast",
    material: "AlSi9Cu3",
    weightKg: 2.46,
    estimate: 16.28,
    target: 19.45,
    programme: "LDT-Urban",
    engineer: "M. Okonkwo",
    region: "EU",
    revision: "B",
    annualVolume: 3872,
    date: "2026-04-15",
  },
  {
    name: "Steering Cover",
    number: "DTV-CVR-2948",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 0.62,
    estimate: 6.7,
    target: null,
    programme: "BEV-PLT-2",
    engineer: "Design Operator",
    region: "India",
    revision: "C",
    annualVolume: 39113,
    date: "2026-03-15",
  },
  {
    name: "Radiator Pan",
    number: "DTV-PAN-3032",
    process: "Die cast",
    material: "AlSi9Cu3",
    weightKg: 5.66,
    estimate: 37.68,
    target: 46.57,
    programme: "HDT-2027",
    engineer: "R. Ehlers",
    region: "Mexico",
    revision: "B",
    annualVolume: 6194,
    date: "2026-02-27",
  },
  {
    name: "Brake Housing",
    number: "DTV-HSG-9918",
    process: "Die cast",
    material: "AZ91D",
    weightKg: 0.92,
    estimate: 8.43,
    target: 7.1,
    programme: "HDT-2027",
    engineer: "Design Operator",
    region: "Turkey",
    revision: "A",
    annualVolume: 5119,
    date: "2026-06-08",
  },
  {
    name: "Radiator Pan",
    number: "DTV-PAN-6605",
    process: "Die cast",
    material: "AlSi9Cu3",
    weightKg: 3.84,
    estimate: 23.82,
    target: 30.78,
    programme: "HDT-2027",
    engineer: "M. Okonkwo",
    region: "India",
    revision: "A",
    annualVolume: 5571,
    date: "2026-03-12",
  },
  {
    name: "Chassis Bracket",
    number: "DTV-BRK-6160",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 2.59,
    estimate: 18.07,
    target: 16.77,
    programme: "BEV-PLT-2",
    engineer: "R. Ehlers",
    region: "Mexico",
    revision: "B",
    annualVolume: 13882,
    date: "2026-03-13",
  },
  {
    name: "Gearbox End Cap",
    number: "DTV-CAP-9732",
    process: "Die cast",
    material: "Zamak 5",
    weightKg: 2.25,
    estimate: 15.97,
    target: 13.48,
    programme: "MDT-2026",
    engineer: "M. Okonkwo",
    region: "Turkey",
    revision: "A",
    annualVolume: 6881,
    date: "2026-04-24",
  },
  {
    name: "Filter End Cap",
    number: "DTV-CAP-8178",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 7.19,
    estimate: 44.42,
    target: 59.18,
    programme: "MDT-2026",
    engineer: "R. Ehlers",
    region: "EU",
    revision: "A",
    annualVolume: 8763,
    date: "2026-06-27",
  },
  {
    name: "Brake Housing",
    number: "DTV-HSG-9557",
    process: "Die cast",
    material: "AlSi9Cu3",
    weightKg: 5.28,
    estimate: 35.23,
    target: 30.21,
    programme: "BEV-PLT-2",
    engineer: "M. Okonkwo",
    region: "EU",
    revision: "B",
    annualVolume: 808,
    date: "2026-07-18",
  },
  {
    name: "Steering Cover",
    number: "DTV-CVR-1948",
    process: "Die cast",
    material: "AlSi10Mg",
    weightKg: 6.11,
    estimate: 37.43,
    target: 50.96,
    programme: "LDT-Urban",
    engineer: "A. Silva",
    region: "Turkey",
    revision: "A",
    annualVolume: 56286,
    date: "2026-05-09",
  },
];
